#!/usr/bin/env python3
"""Generate ready-to-use @font-face rules for Noisy Mono webfonts."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

UNICODE_RANGES = (
    "U+0000-024F,U+0300-036F,U+1E00-1EFF,U+2000-206F,"
    "U+2070-209F,U+20A0-20CF,U+2100-214F,U+2150-218F,"
    "U+2190-23FF,U+2500-27FF,U+2900-2BFF,U+FB00-FB06,"
    "U+FEFF,U+FFFD"
)

WEIGHTS = {
    "Thin": 100,
    "ExtraLight": 200,
    "Light": 300,
    "SemiLight": 350,
    "Regular": 400,
    "Medium": 500,
    "SemiBold": 600,
    "Bold": 700,
    "ExtraBold": 800,
    "Black": 900,
}

WIDTHS = {
    "": "100%",
    "SemiCondensed": "87.5%",
    "Condensed": "75%",
}

FILENAME_PATTERN = re.compile(
    r"^NoisyMono-(?P<width>SemiCondensed|Condensed)?"
    r"(?P<weight>Thin|ExtraLight|Light|SemiLight|Regular|Medium|SemiBold|Bold|ExtraBold|Black)?"
    r"(?P<italic>Italic)?\.woff2$"
)


def face_properties(font_path: Path) -> tuple[int, str, str]:
    match = FILENAME_PATTERN.match(font_path.name)
    if match is None:
        raise ValueError(f"Unrecognized Noisy Mono filename: {font_path.name}")

    width_name = match.group("width") or ""
    weight_name = match.group("weight") or "Regular"
    style = "italic" if match.group("italic") else "normal"
    return WEIGHTS[weight_name], WIDTHS[width_name], style


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("font_dir", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--url-prefix",
        default="fonts",
        help="URL path prepended to font filenames (default: fonts)",
    )
    args = parser.parse_args()

    font_paths = sorted(args.font_dir.glob("*.woff2"))
    if not font_paths:
        parser.error(f"no WOFF2 files found in {args.font_dir}")

    faces = []
    for font_path in font_paths:
        weight, width, style = face_properties(font_path)
        faces.append((width, weight, style, font_path))

    lines = [
        "/* Generated by scripts/generate-webfont-css.py. */",
        "/* Curated Latin/technical subsets of Noisy Mono. */",
        "",
    ]
    for width, weight, style, font_path in sorted(faces):
        url = f"{args.url_prefix.rstrip('/')}/{font_path.name}"
        lines.extend(
            [
                "@font-face {",
                '  font-family: "Noisy Mono";',
                f'  src: url("{url}") format("woff2");',
                f"  font-style: {style};",
                f"  font-weight: {weight};",
                f"  font-stretch: {width};",
                "  font-display: swap;",
                f"  unicode-range: {UNICODE_RANGES};",
                "}",
                "",
            ]
        )

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
